name: example
description: Exemple of MultiListenableBuilder usage.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_listenable: 0.9.2
