name: multi_listenable
description: A widget whose content stays synced with a list of Listenable.
version: 0.9.3
homepage: https://github.com/epo33/multi_listenable

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
